### ISSUE TITLE
Not all buttons bind on keyboard and mouse?

### ISSUE THREAD

**Issue by dante3732** [argonlefou/TSR_Loader#1]
I couldn't find the start button for the first player only, as well as the forward and backward lever. Are subtitles only available in English?

**Comment by argonlefou** [comment]
> I couldn't find the start button for the first player only, as well as the forward and backward lever. 

The loader does just boot the game, and is not handling inputs ans controls, DemulShooter is needed for that part.

I will add a notice on the github page.

> Are subtitles only available in English?

I don't know, there may be some other language (or not) and some country/region selection (or not) but it's not in the Service menu

I shared every details I could found (and to be honest I didn't search for other region/languages)

**Comment by dante3732** [comment]
I completed game with demulshooter, it work fine, but I have framedrops.
Thanks for launcher.
Do you happen to know the characteristics of the arcade cabinet? The game consumes quite a lot of resources, unlike ring edge 2.

**Comment by argonlefou** [comment]
Unfortunately no, I got all the info from the [operator manual](https://files.winwithp1ag.com/products/video-games/shooting/Sega-Transformers-Shadows-Rising-Manual.pdf)

Ring edge 2 is mentionned in it, but I've read somewhere that it is not true and that the board is nor RE2 in reality

I'm not in the arcade business and can't have acces to real hardware (I wish I did !)
